meta_product_name: "Level Up"
meta_title: "Stay on track and Level Up"
meta_description: "Level Up helps you keep track of the skills you're trying to improve"
meta_image: "Studio_Project.jpeg" # should exist in `app/assets/images/`